server:
  port: 8088

# 服务名称
spring:
  application:
    name: gateway
  # 网关配置
  cloud:
    gateway:
      # 全局配置
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 *表示通配 允许所有的域 实际可以填写ip
            allowedHeaders: "*"
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      # 网关路由配置
      routes:
        #id是个列表 有多个路由配置时就写多个id及下面的配置，以下是完整的一个
        - id: interact # 路由id 唯一标识
          uri: lb://interact # 路由地址，动态路由  lb是一个网关的协议
          predicates: # 断言
            - Path=/interact/**,/index/**,/place/**,/scene/**,/user/**

        - id: auth # 路由id 唯一标识
          uri: lb://auth # 路由地址，动态路由  lb是一个网关的协议
          predicates: # 断言
            - Path=/userAuth/**,/log/**

    nacos:
      discovery:
#        server-addr: 101.133.230.219:8848
        server-addr: 127.0.0.1:8848



